@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR
skinparam packageStyle rectangle
hide empty members

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6 {
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "TaskForge Storage" #F4F6F6 {
Class "<<interface>>\nTaskForgeStorage" as TaskForgeStorage
Class JsonTaskForgeStorage
Class JsonSerializableTaskForge
Class JsonAdaptedPerson
Class JsonAdaptedProject
Class JsonAdaptedTask
Class JsonAdaptedPersonProject
Class JsonAdaptedPersonTask
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" TaskForgeStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> TaskForgeStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonTaskForgeStorage .up.|> TaskForgeStorage
JsonTaskForgeStorage ..> JsonSerializableTaskForge

JsonSerializableTaskForge --> "*" JsonAdaptedPerson
JsonSerializableTaskForge --> "*" JsonAdaptedProject

JsonAdaptedProject --> "*" JsonAdaptedTask
JsonAdaptedPerson --> "*" JsonAdaptedPersonProject
JsonAdaptedPerson --> "*" JsonAdaptedPersonTask

@enduml
