@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedTaskForge" as VersionedTaskForge MODEL_COLOR
end box

[-> Model : undoTaskForge()
activate Model

Model -> VersionedTaskForge : undo()
activate VersionedTaskForge

VersionedTaskForge -> VersionedTaskForge :resetData(ReadOnlyTaskForge)
VersionedTaskForge --> Model :
deactivate VersionedTaskForge

[<-- Model
deactivate Model

@enduml
