@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TaskForgeParser" as TaskForgeParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> TaskForgeParser : parseCommand(undo)
activate TaskForgeParser

create UndoCommand
TaskForgeParser -> UndoCommand
activate UndoCommand

UndoCommand --> TaskForgeParser
deactivate UndoCommand

TaskForgeParser --> LogicManager : u
deactivate TaskForgeParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoTaskForge()
activate Model

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
